### ISSUE TITLE
Add DEP Token Logo In GuildChat App

### ISSUE THREAD

**Issue by DEPFoundation** [BitGuildPlatform/dapps#1]
Please add DEP Token logo in GuildChat app. 
Token Type - TRC10
Token ID- 1001909
Token Name- DEP
Token URL- https://tronscan.org/#/token/1001909
![photo_2019-01-19_15-21-46](https://user-images.githubusercontent.com/46860176/59603561-5b1ead80-9127-11e9-999f-165af3074fce.jpg)

I attached the token logo please add this. 

If is it possible please change the name of dep to DEP in GuildChat.

**Comment by ririen** [comment]
The image of the token is already available in the repository.

`https://github.com/BitGuildPlatform/dapps/blob/master/tron/trc10/1001909.png`

`https://raw.githubusercontent.com/BitGuildPlatform/dapps/master/tron/trc10/1001909.png`

**Comment by DEPFoundation** [comment]
Then why it does't show in app ? 
![photo_2019-06-17_18-11-20](https://user-images.githubusercontent.com/46860176/59605025-6673d800-912b-11e9-8ce7-ce6b34917ed7.jpg)

**Comment by Rovak** [comment]
GuildChat hasn't been updated yet to use this repository. Only TronTrade and GuildWallet fetch icons from this repository

**Comment by DEPFoundation** [comment]
Ok thank you

**Comment by DEPFoundation** [comment]
DEP logo does't show in coin pouch section but it shows in wallet section and also please add SHINE logo in guildchat. Token Contract Address - TZCNuXEbM5APFnBa5k4DwYBs2D6jn4xKkS
Link - https://tronscan.org/#/token20/TC4X34Ga9vvYTfBpMzdNyprKgWzJ86GMSX
